Add cloudwatch logs support

diff --git a/am b/am
--- a/am
+++ b/am
@@ -1,7 +1,14 @@
 #!/bin/bash
-prog="${0##*/}"
-[ ${#} -eq 0 ] && echo "usage: ${prog} <hostname> [command]" && exit 1
-[ ${prog} == "amp" ] && fast="-f"
+
+while getopts ":pl" opt; do
+  case ${opt} in
+    "p") fast="-f";;
+    "l") logs="1";;
+    "?") echo "Invalid option: -${OPTARG}" && exit 1;;
+  esac
+done
+shift $((${OPTIND} - 1))
+[ ${#} -eq 0 ] && echo "usage: am [-p|-l] <hostname> [command]" && exit 1
 
 # change the default region if hostname starts with us-
 [ "${1:0:3}" == "us-" ] && region="--region us-west-2"
@@ -25,20 +32,38 @@ results=$(
     --cli-read-timeout 0
 )
 
-# print a table of matching hosts if only hostname entered
-if [ ${#} -eq 1 ]; then
-  echo ${results} | jq -r '.[] | [.name, .id, .ip, .az, .type, .ami, (.role|split("/")?|last) ] | join(" ")' | column -t
+# print the cloudwatch logs for the matching hosts
+if [ "${logs}" ]; then
+  while [ 1 ]; do
+    log=$(
+      aws logs filter-log-events \
+        --log-group-name /var/log/syslog \
+        --interleaved \
+        --log-stream-names $(echo ${results} | jq -r '.[] .name') \
+        --start-time $(($(date +%s) * 1000 - 15000)) \
+        --max-items 15 \
+        ${next_token}
+    )
+    next_token=$(echo ${log} | jq -r '.NextToken // empty')
+    [ "${next_token}" ] && next_token="--starting-token ${next_token}"
+    echo ${log} | jq -r '.events[].message'
+    sleep 4
+  done
 
 # else run a command remotely on matching hosts
-else
+elif [ ${#} -gt 1 ]; then
   shift # drop hostname
   cmd="${@}"
   if grep -q "sudo " <<< "${cmd}"; then
-    read -p "[${prog}] sudo password: " -s password; echo
+    read -p "[am] sudo password: " -s password; echo
     cmd=${cmd//sudo/"echo \"${password}\" | sudo -p' ' -S"}
   fi
   for i in $(echo ${results} | jq -r '.[] | .ip'); do
     echo "* ${i}: ${@}"
     ssh ${fast} -t -q -o ConnectTimeout=10 -o StrictHostKeyChecking=no ${i} -- "${cmd}" || echo "Exited: ${?}"
   done
+
+# else print out the results
+else
+  echo ${results} | jq -r '.[] | [.name, .id, .ip, .az, .type, .ami, (.role|split("/")?|last) ] | join(" ")' | column -t
 fi
